//In This page i am practice to handle the errors. 
//Handle error with try{} an catch(){}.

let a=5;
let b=10;

console.log("a = ",a);
console.log("b = ",b);

console.log(a+b)
console.log(a+b)
//this lins come error and another console has not print 
//solution is
try{

    console.log(a+c)
}
catch(err){
console.log(err)
}
console.log(a+b)
console.log(a+b)
console.log(a+b)
console.log(a+b)
console.log(a+b)

//So  this trick use to handle the Error  



